# Generated by Django 6.0.3 on 2026-03-20 22:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pass', '0001_initial'),
        ('Payments', '0002_remove_payment_user_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pass',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_pass', to='Payments.payment'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='pass_code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
